owner: ssciwr
repo: monitoring

sites:
  - name: SSC
    url: https://ssc.uni-heidelberg.de
  - name: MONDEY
    url: https://mondey.de
  - name: MONDEY backend
    url: https://mondey.de/api/languages/
    method: GET
  - name: PredicTCR
    url: https://predictcr.com
  - name: PredicTCR backend
    url: https://predictcr.com/api/settings
    method: GET
  - name: SampleFlow
    url: https://circuitseq.iwr.uni-heidelberg.de/
  - name: SampleFlow backend
    url: https://circuitseq.iwr.uni-heidelberg.de/api/remaining
    method: GET

status-website:
  baseUrl: /monitoring
  logoUrl: https://backend.ssc.uni-heidelberg.de/sites/default/files/site_logo/WEB%20Kopfgrafik%20Scientific-Software-Center%20LANG%20neu_0.svg
  favicon: https://raw.githubusercontent.com/ssciwr/monitoring/refs/heads/main/assets/favicon.ico
  name: SSC web service monitoring
  introTitle: ""
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "17 00 * * *"
  responseTime: "03 23 * * *"
  staticSite: "09 1 * * *"
  summary: "11 0 * * *"
  updateTemplate: "7 0 * * *"
  updates: "11 3 * * *"
  uptime: "3,18,33,48 * * * *"