owner: lkeegan
repo: monitoring

sites:
  - name: SSC
    url: https://ssc.uni-heidelberg.de
  - name: MONDEY
    url: https://mondey.de
  - name: PredicTCR
    url: https://predictcr.com
  - name: SampleFlow
    url: https://circuitseq.iwr.uni-heidelberg.de/

status-website:
  baseUrl: /monitoring
  logoUrl: https://backend.ssc.uni-heidelberg.de/sites/default/files/site_logo/WEB%20Kopfgrafik%20Scientific-Software-Center%20LANG%20neu_0.svg
  name: SSC web service monitoring
  introTitle: ""
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO